@echo off
REM ============================================
REM  SwiftShot Launcher
REM  Auto-generated by Install-SwiftShot.ps1
REM ============================================
cd /d "%~dp0"
start "" "C:\Users\--\Downloads\swiftshot_upload\.venv\Scripts\pythonw.exe" "%~dp0main.py" %*
