' SwiftShot Silent Launcher - No console window at all
' Auto-generated by Install-SwiftShot.ps1
Set WshShell = CreateObject("WScript.Shell")
WshShell.CurrentDirectory = "C:\\Users\\--\\Downloads\\swiftshot_upload"
WshShell.Run """C:\\Users\\--\\Downloads\\swiftshot_upload\\.venv\\Scripts\\pythonw.exe"" ""C:\\Users\\--\\Downloads\\swiftshot_upload\\main.py""", 0, False
Set WshShell = Nothing
